
server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 2
            redis-rate-limiter.burstCapacity: 3
            key-resolver: "#{@customRateKeyResolver}"
      routes:
        - id: service-hello
          uri: http://localhost:8081
          predicates:
            - Path=/api/hello
logging:
  level:
    org.springframework.cloud.gateway.filter.ratelimit: DEBUG
