server:
  port: 8080

spring:
  application:
    name: api-gateway
  redis:
    host: localhost
    port: 6379

  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 50
            redis-rate-limiter.burstCapacity: 50
            key-resolver: "#{@ipAndPathKeyResolver}"
      routes:
        - id: service-hello
          uri: http://localhost:8081
          predicates:
            - Path=/api/hello
  main:
    allow-bean-definition-overriding: true
