server:
  port: 8080

spring:
  application:
    name: api-gateway

  redis:
    host: localhost
    port: 6379

  main:
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 5
            redis-rate-limiter.burstCapacity: 50
            key-resolver: "#{@customRateKeyResolver}"
      routes:
        - id: service-hello
          uri: http://localhost:8081
          predicates:
            - Path=/api/hello

logging:
  level:
    org.springframework.cloud.gateway.filter.ratelimit: DEBUG
